package com.example.studentmanagement.utils;

public enum MyFuncButton {
    ADMIN_FACULTY_MANAGEMENT,
    ADMIN_COURSE_MANAGEMENT,
    ADMIN_LECTURER_MANAGEMENT,
    ADMIN_PRACTICALCLASS_MANAGEMENT,
    ADMIN_STUDENT_MANAGEMENT,
    EDIT_FACULTY,
    VIEW_FACULTY,
    VIEW_LECTURER,
    EDIT_LECTURER,
    VIEW_COURSE,
    EDIT_COURSE,
    VIEW_PRACTICAL_CLASS,
    EDIT_PRACTICAL_CLASS,
    VIEW_STUDENT,
    EDIT_STUDENT
}
